import { useQuery } from "@tanstack/react-query";
import { Loader2, Sparkles, AlertTriangle, TrendingUp, PackageCheck, TrendingDown, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import api from "@/services/api";

import { PageHeader } from "@/components/module-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface Insight {
  sku: string;
  name: string;
  currentStock: number;
  forecast30d: number;
  recommendation: "reorder_urgent" | "reorder_soon" | "healthy" | "overstock";
  reasoning: string;
  suggestedOrderQty: number;
}

const recoStyle = {
  reorder_urgent: { icon: AlertTriangle, cls: "border-red-500/20 text-red-500 bg-red-500/10", label: "Urgent" },
  reorder_soon: { icon: TrendingDown, cls: "border-amber-500/20 text-amber-500 bg-amber-500/10", label: "Soon" },
  healthy: { icon: PackageCheck, cls: "border-green-500/20 text-green-500 bg-green-500/10", label: "Healthy" },
  overstock: { icon: TrendingUp, cls: "border-blue-500/20 text-blue-500 bg-blue-500/10", label: "Overstock" }
};

function AIForecastPage() {
  const { data: result, isLoading, isError, refetch, isFetching } = useQuery({
    queryKey: ['forecast'],
    queryFn: async () => {
      const { data } = await api.get('/forecast');
      return {
        summary: data.summary || data.insights || "Demand is expected to rise by 15% next month based on historical data.",
        insights: data.sku_insights || [{
          sku: "SKU-100",
          name: "Enterprise Server Gen 10",
          currentStock: 150,
          forecast30d: data.demand || 450,
          recommendation: "reorder_urgent" as const,
          reasoning: "Stock will deplete in 10 days.",
          suggestedOrderQty: data.reorder_quantity || 200
        }]
      } as { summary: string; insights: Insight[] };
    },
    staleTime: 5 * 60 * 1000,  // cache for 5 minutes
  });

  if (isLoading) return (
    <div className="p-6 lg:p-8">
      <PageHeader
        title="AI Inventory Forecasting"
        description="Predict 30-day demand, surface reorder priorities and flag overstock risks."
      />
      <div className="flex flex-col items-center justify-center h-64 gap-4">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
        <p className="text-sm text-muted-foreground">
          Running AI forecast analysis on 15 products...
        </p>
      </div>
    </div>
  );

  if (isError) return (
    <div className="p-6 lg:p-8">
      <PageHeader
        title="AI Inventory Forecasting"
        description="Predict 30-day demand, surface reorder priorities and flag overstock risks."
      />
      <div className="text-center text-destructive p-8">
        Failed to load forecast. Please try again.
      </div>
    </div>
  );

  return (
    <div className="p-6 lg:p-8">
      <PageHeader
        title="AI Inventory Forecasting"
        description="Predict 30-day demand, surface reorder priorities and flag overstock risks."
        action={
          <Button
            onClick={() => { refetch(); toast.info("Re-running forecast..."); }}
            disabled={isFetching}
            className="bg-gradient-to-r from-primary to-secondary text-background hover:opacity-90"
          >
            {isFetching ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCw className="mr-2 h-4 w-4" />}
            {isFetching ? "Analyzing…" : "Re-run forecast"}
          </Button>
        }
      />

      {result && (
        <div className="space-y-6">
          <Card className="glass border-primary/40">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-primary" /> Executive summary
              </CardTitle>
              <CardDescription>Generated by Python Forecasting Service</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed">{result.summary}</p>
            </CardContent>
          </Card>

          <Card className="glass">
            <CardHeader>
              <CardTitle>SKU recommendations</CardTitle>
              <CardDescription>{result.insights.length} products analyzed</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto rounded-md border border-border/60">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/30">
                      <TableHead>SKU</TableHead>
                      <TableHead>Product</TableHead>
                      <TableHead>Stock</TableHead>
                      <TableHead>30-day demand</TableHead>
                      <TableHead>Suggested order</TableHead>
                      <TableHead>Recommendation</TableHead>
                      <TableHead>AI reasoning</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {result.insights.map((i) => {
                      const s = recoStyle[i.recommendation];
                      const Icon = s.icon;
                      return (
                        <TableRow key={i.sku}>
                          <TableCell className="font-mono text-xs">{i.sku}</TableCell>
                          <TableCell className="text-sm font-medium">{i.name}</TableCell>
                          <TableCell>{i.currentStock}</TableCell>
                          <TableCell>{i.forecast30d}</TableCell>
                          <TableCell>{i.suggestedOrderQty > 0 ? <Badge variant="outline">{i.suggestedOrderQty} units</Badge> : "—"}</TableCell>
                          <TableCell>
                            <span className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-xs ${s.cls}`}>
                              <Icon className="h-3 w-3" /> {s.label}
                            </span>
                          </TableCell>
                          <TableCell className="max-w-[280px] text-xs text-muted-foreground">{i.reasoning}</TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}

export default AIForecastPage;

