// @ts-nocheck
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Brain, Loader2, Sparkles, AlertTriangle, TrendingUp, PackageCheck, TrendingDown } from "lucide-react";
import { toast } from "sonner";
import api from "@/services/api";

import { PageHeader } from "@/components/module-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface Insight {
  sku: string;
  name: string;
  currentStock: number;
  forecast30d: number;
  recommendation: "reorder_urgent" | "reorder_soon" | "healthy" | "overstock";
  reasoning: string;
  suggestedOrderQty: number;
}

const recoStyle = {
  reorder_urgent: { icon: AlertTriangle, cls: "border-red-500/20 text-red-500 bg-red-500/10", label: "Urgent" },
  reorder_soon: { icon: TrendingDown, cls: "border-amber-500/20 text-amber-500 bg-amber-500/10", label: "Soon" },
  healthy: { icon: PackageCheck, cls: "border-green-500/20 text-green-500 bg-green-500/10", label: "Healthy" },
  overstock: { icon: TrendingUp, cls: "border-blue-500/20 text-blue-500 bg-blue-500/10", label: "Overstock" }
};

function AIForecastPage() {
  const [result, setResult] = useState<{ summary: string; insights: Insight[] } | null>(null);

  const mutation = useMutation({
    mutationFn: async () => {
      const { data } = await api.get('/forecast');
      return {
        summary: data.insights || "Demand is expected to rise by 15% next month based on historical data.",
        insights: [
            {
                sku: "SKU-100",
                name: "Enterprise Server Gen 10",
                currentStock: 150,
                forecast30d: data.demand || 450,
                recommendation: "reorder_urgent",
                reasoning: "Stock will deplete in 10 days.",
                suggestedOrderQty: data.reorder_quantity || 200
            }
        ]
      } as { summary: string; insights: Insight[] };
    },
    onSuccess: (data) => { setResult(data); toast.success(`Analyzed ${data.insights.length} SKUs`); },
    onError: (e: Error) => toast.error(e.message),
  });

  return (
    <div className="p-6 lg:p-8">
      <PageHeader
        title="AI Inventory Forecasting"
        description="Predict 30-day demand, surface reorder priorities and flag overstock risks."
        action={
          <Button onClick={() => mutation.mutate()} disabled={mutation.isPending}
            className="bg-gradient-to-r from-primary to-secondary text-background hover:opacity-90">
            {mutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
            {mutation.isPending ? "Analyzing…" : "Run forecast"}
          </Button>
        }
      />

      {!result && !mutation.isPending && (
        <Card className="glass">
          <CardContent className="py-16 text-center">
            <Brain className="mx-auto h-10 w-10 text-primary" />
            <h3 className="mt-4 text-lg font-semibold">Ready when you are</h3>
            <p className="mt-1 text-sm text-muted-foreground">
              Click <strong>Run forecast</strong> to analyze your current SKU stock levels.
            </p>
          </CardContent>
        </Card>
      )}

      {mutation.isPending && (
        <Card className="glass">
          <CardContent className="py-16 text-center">
            <Loader2 className="mx-auto h-10 w-10 animate-spin text-primary" />
            <p className="mt-4 text-sm text-muted-foreground">Running demand forecast across your catalog…</p>
          </CardContent>
        </Card>
      )}

      {result && (
        <div className="space-y-6">
          <Card className="glass border-primary/40">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-primary" /> Executive summary
              </CardTitle>
              <CardDescription>Generated by Python Forecasting Service</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed">{result.summary}</p>
            </CardContent>
          </Card>

          <Card className="glass">
            <CardHeader>
              <CardTitle>SKU recommendations</CardTitle>
              <CardDescription>{result.insights.length} products analyzed</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto rounded-md border border-border/60">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/30">
                      <TableHead>SKU</TableHead>
                      <TableHead>Product</TableHead>
                      <TableHead>Stock</TableHead>
                      <TableHead>30-day demand</TableHead>
                      <TableHead>Suggested order</TableHead>
                      <TableHead>Recommendation</TableHead>
                      <TableHead>AI reasoning</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {result.insights.map((i) => {
                      const s = recoStyle[i.recommendation];
                      const Icon = s.icon;
                      return (
                        <TableRow key={i.sku}>
                          <TableCell className="font-mono text-xs">{i.sku}</TableCell>
                          <TableCell className="text-sm font-medium">{i.name}</TableCell>
                          <TableCell>{i.currentStock}</TableCell>
                          <TableCell>{i.forecast30d}</TableCell>
                          <TableCell>{i.suggestedOrderQty > 0 ? <Badge variant="outline">{i.suggestedOrderQty} units</Badge> : "—"}</TableCell>
                          <TableCell>
                            <span className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-xs ${s.cls}`}>
                              <Icon className="h-3 w-3" /> {s.label}
                            </span>
                          </TableCell>
                          <TableCell className="max-w-[280px] text-xs text-muted-foreground">{i.reasoning}</TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}

export default AIForecastPage;
